name: ci

on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o repositório
        uses: actions/checkout@v4

      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install poetry
        run: pip install poetry

      - name: Install requirements
        run: poetry install

      - name: rodar minha rotina de testes
        run: pytest tests\test.py -v
